TieBreaker AI: src.train_outcome Namespace Reference
src.train_outcome Namespace Reference
Classes
class DatasetSplits
class SplitConfig
class TrainingArtifacts
Functions
argparse.Namespace parse_args (list[str]|None argv=None)
Dict[str, Any] _parse_xgb_params (str|None raw)
pd.DataFrame load_dataset (Path data_path)
list[str] get_feature_columns (pd.DataFrame df)
list[int] get_available_years (pd.DataFrame df)
SplitConfig resolve_split_config (list[int] years, int|None train_arg, int|None val_arg)
tuple[pd.Series, pd.Series, pd.Series] _build_row_split_masks (pd.DataFrame df, int first_year, int test_year, int seed)
DatasetSplits build_splits (pd.DataFrame df, list[str] feature_cols, SplitConfig split_cfg, list[int] years, int seed)
np.ndarray|None compute_recency_weights (pd.Series years, int reference_year, float|None half_life)
Tuple[Any, str] init_classifier (int seed, Dict[str, Any] overrides)
Tuple[Any, np.ndarray|None, np.ndarray|None] train_classifier (Any model, SimpleImputer imputer, DatasetSplits splits, np.ndarray|None sample_weight)
Tuple[Any, str|None] calibrate_model (Any base_model, np.ndarray|None X_cal, np.ndarray|None y_cal, str method)
Dict[str, Any] evaluate_split (Pipeline model, pd.DataFrame X, pd.Series y)
Pipeline build_final_pipeline (SimpleImputer imputer, Any model)
None save_metrics (Path report_path, Dict[str, Any] metrics)
None save_model (Path model_path, Dict[str, Any] bundle)
TrainingArtifacts train_pipeline (argparse.Namespace args)
int main (list[str]|None argv=None)
Variables
LOGGER = logging.getLogger(__name__)
level
INFO
format
dict EXCLUDE_COLUMNS
Detailed Description
Model training entrypoint for TieBreaker outcome prediction.
Function Documentation
_build_row_split_masks()
tuple[pd.Series, pd.Series, pd.Series] src.train_outcome._build_row_split_masks (pd.DataFrame df, int first_year, int test_year, int seed) protected
Definition at line 210 of file train_outcome.py.
Referenced by src.train_outcome.build_splits().
_parse_xgb_params()
Dict[str, Any] src.train_outcome._parse_xgb_params (str | None raw) protected
Definition at line 107 of file train_outcome.py.
Referenced by src.train_outcome.train_pipeline().
build_final_pipeline()
Pipeline src.train_outcome.build_final_pipeline (SimpleImputer imputer, Any model)
Definition at line 402 of file train_outcome.py.
Referenced by src.train_outcome.train_pipeline().
build_splits()
DatasetSplits src.train_outcome.build_splits (pd.DataFrame df, list[str] feature_cols, SplitConfig split_cfg, list[int] years, int seed)
Definition at line 238 of file train_outcome.py.
References src.train_outcome._build_row_split_masks().
Referenced by src.train_outcome.train_pipeline().
calibrate_model()
Tuple[Any, str | None] src.train_outcome.calibrate_model (Any base_model, np.ndarray | None X_cal, np.ndarray | None y_cal, str method)
Definition at line 351 of file train_outcome.py.
Referenced by src.train_outcome.train_pipeline().
compute_recency_weights()
np.ndarray | None src.train_outcome.compute_recency_weights (pd.Series years, int reference_year, float | None half_life)
Definition at line 285 of file train_outcome.py.
Referenced by src.train_outcome.train_pipeline().
evaluate_split()
Dict[str, Any] src.train_outcome.evaluate_split (Pipeline model, pd.DataFrame X, pd.Series y)
Definition at line 387 of file train_outcome.py.
Referenced by src.train_outcome.train_pipeline().
get_available_years()
list[int] src.train_outcome.get_available_years (pd.DataFrame df)
Definition at line 144 of file train_outcome.py.
Referenced by src.train_outcome.train_pipeline().
get_feature_columns()
list[str] src.train_outcome.get_feature_columns (pd.DataFrame df)
Definition at line 135 of file train_outcome.py.
Referenced by src.train_outcome.train_pipeline().
init_classifier()
Tuple[Any, str] src.train_outcome.init_classifier (int seed, Dict[str, Any] overrides)
Definition at line 298 of file train_outcome.py.
Referenced by src.train_outcome.train_pipeline().
load_dataset()
pd.DataFrame src.train_outcome.load_dataset (Path data_path)
Definition at line 119 of file train_outcome.py.
Referenced by src.train_outcome.train_pipeline().
main()
int src.train_outcome.main (list[str] | None argv = None)
Definition at line 483 of file train_outcome.py.
References src.train_outcome.parse_args(), src.train_outcome.save_metrics(), src.train_outcome.save_model(), and src.train_outcome.train_pipeline().
parse_args()
argparse.Namespace src.train_outcome.parse_args (list[str] | None argv = None)
Definition at line 79 of file train_outcome.py.
Referenced by src.train_outcome.main().
resolve_split_config()
SplitConfig src.train_outcome.resolve_split_config (list[int] years, int | None train_arg, int | None val_arg)
Definition at line 157 of file train_outcome.py.
Referenced by src.train_outcome.train_pipeline().
save_metrics()
None src.train_outcome.save_metrics (Path report_path, Dict[str, Any] metrics)
Definition at line 409 of file train_outcome.py.
Referenced by src.train_outcome.main().
save_model()
None src.train_outcome.save_model (Path model_path, Dict[str, Any] bundle)
Definition at line 416 of file train_outcome.py.
Referenced by src.train_outcome.main().
train_classifier()
Tuple[Any, np.ndarray | None, np.ndarray | None] src.train_outcome.train_classifier (Any model, SimpleImputer imputer, DatasetSplits splits, np.ndarray | None sample_weight)
Definition at line 318 of file train_outcome.py.
Referenced by src.train_outcome.train_pipeline().
train_pipeline()
TrainingArtifacts src.train_outcome.train_pipeline (argparse.Namespace args)
Definition at line 422 of file train_outcome.py.
References src.train_outcome._parse_xgb_params(), src.train_outcome.build_final_pipeline(), src.train_outcome.build_splits(), src.train_outcome.calibrate_model(), src.train_outcome.compute_recency_weights(), src.train_outcome.evaluate_split(), src.train_outcome.get_available_years(), src.train_outcome.get_feature_columns(), src.train_outcome.init_classifier(), src.train_outcome.load_dataset(), src.train_outcome.resolve_split_config(), and src.train_outcome.train_classifier().
Referenced by src.train_outcome.main().
Variable Documentation
EXCLUDE_COLUMNS
dict src.train_outcome.EXCLUDE_COLUMNS
Initial value:
=  {
    "y",
    "A_name",
    "B_name",
    "A_player_id",
    "B_player_id",
    "winner_name_raw",
    "loser_name_raw",
    "tourney_name",
    "tourney_date",
    "year",
}
Definition at line 36 of file train_outcome.py.
format
src.train_outcome.format
Definition at line 29 of file train_outcome.py.
INFO
src.train_outcome.INFO
Definition at line 29 of file train_outcome.py.
level
src.train_outcome.level
Definition at line 29 of file train_outcome.py.
LOGGER
src.train_outcome.LOGGER = logging.getLogger(__name__)
Definition at line 28 of file train_outcome.py.