TieBreaker AI: src.predict_outcome Namespace Reference
src.predict_outcome Namespace Reference
Classes
class PredictRequest
class PredictResult
Functions
pd.DataFrame add_recent_form_features (pd.DataFrame matches_df, pd.DataFrame dataset, **Any _)
PredictResult predict_outcome (PredictRequest req)
pd.Timestamp _resolve_target_date (Optional[pd.Timestamp] date_value, Optional[int] default_year)
tuple[int, str] _resolve_player (pd.DataFrame players_df, str query)
pd.DataFrame _filter_matches_for_players (pd.DataFrame matches_df, set[int] player_ids)
pd.DataFrame _load_matches_for_prediction (DataHub hub, pd.Timestamp target_date, set[int] player_ids, int window_years=5)
Optional[int] _safe_int (Any value)
int _default_best_of (PredictRequest req)
Optional[int] _infer_best_of_from_matches (pd.DataFrame matches_df, str p1_name, str p2_name, pd.Timestamp target_date, Optional[str] surface, Optional[str] round_value)
tuple[int, str] _resolve_best_of (PredictRequest req, pd.DataFrame matches_df, str p1_name, str p2_name, pd.Timestamp target_date)
Dict[str, Any] _build_base_feature_row (int p1_id, str p1_name, int p2_id, str p2_name, pd.Timestamp target_date, PredictRequest req, pd.DataFrame rankings_df, PlayerLookup lookup)
str _norm (str value)
str _clean_surface (Optional[str] surface)
str _clean_round (Optional[str] round_value)
Variables
dict RECENT_FEATURE_MAP = {}
Detailed Description
One-off outcome prediction utilities for TieBreaker.
Function Documentation
_build_base_feature_row()
Dict[str, Any] src.predict_outcome._build_base_feature_row (int p1_id, str p1_name, int p2_id, str p2_name, pd.Timestamp target_date, PredictRequest req, pd.DataFrame rankings_df, PlayerLookup lookup) protected
Definition at line 317 of file predict_outcome.py.
References src.predict_outcome._clean_round(), and src.predict_outcome._clean_surface().
Referenced by src.predict_outcome.predict_outcome().
_clean_round()
str src.predict_outcome._clean_round (Optional[str] round_value) protected
Definition at line 356 of file predict_outcome.py.
Referenced by src.predict_outcome._build_base_feature_row().
_clean_surface()
str src.predict_outcome._clean_surface (Optional[str] surface) protected
Definition at line 347 of file predict_outcome.py.
Referenced by src.predict_outcome._build_base_feature_row().
_default_best_of()
int src.predict_outcome._default_best_of (PredictRequest req) protected
Definition at line 241 of file predict_outcome.py.
Referenced by src.predict_outcome._resolve_best_of().
_filter_matches_for_players()
pd.DataFrame src.predict_outcome._filter_matches_for_players (pd.DataFrame matches_df, set[int] player_ids) protected
Definition at line 200 of file predict_outcome.py.
Referenced by src.predict_outcome._load_matches_for_prediction().
_infer_best_of_from_matches()
Optional[int] src.predict_outcome._infer_best_of_from_matches (pd.DataFrame matches_df, str p1_name, str p2_name, pd.Timestamp target_date, Optional[str] surface, Optional[str] round_value) protected
Definition at line 252 of file predict_outcome.py.
References src.predict_outcome._safe_int().
Referenced by src.predict_outcome._resolve_best_of().
_load_matches_for_prediction()
pd.DataFrame src.predict_outcome._load_matches_for_prediction (DataHub hub, pd.Timestamp target_date, set[int] player_ids, int window_years = 5) protected
Definition at line 212 of file predict_outcome.py.
References src.predict_outcome._filter_matches_for_players().
Referenced by src.predict_outcome.predict_outcome().
_norm()
str src.predict_outcome._norm (str value) protected
Definition at line 343 of file predict_outcome.py.
Referenced by src.predict_outcome._resolve_player().
_resolve_best_of()
tuple[int, str] src.predict_outcome._resolve_best_of (PredictRequest req, pd.DataFrame matches_df, str p1_name, str p2_name, pd.Timestamp target_date) protected
Definition at line 301 of file predict_outcome.py.
References src.predict_outcome._default_best_of(), src.predict_outcome._infer_best_of_from_matches(), and src.predict_outcome._safe_int().
Referenced by src.predict_outcome.predict_outcome().
_resolve_player()
tuple[int, str] src.predict_outcome._resolve_player (pd.DataFrame players_df, str query) protected
Definition at line 180 of file predict_outcome.py.
References src.predict_outcome._norm().
Referenced by src.predict_outcome.predict_outcome().
_resolve_target_date()
pd.Timestamp src.predict_outcome._resolve_target_date (Optional[pd.Timestamp] date_value, Optional[int] default_year) protected
Definition at line 172 of file predict_outcome.py.
Referenced by src.predict_outcome.predict_outcome().
_safe_int()
Optional[int] src.predict_outcome._safe_int (Any value) protected
Definition at line 229 of file predict_outcome.py.
Referenced by src.predict_outcome._infer_best_of_from_matches(), and src.predict_outcome._resolve_best_of().
add_recent_form_features()
pd.DataFrame src.predict_outcome.add_recent_form_features (pd.DataFrame matches_df, pd.DataFrame dataset, **Any _)
Definition at line 44 of file predict_outcome.py.
predict_outcome()
PredictResult src.predict_outcome.predict_outcome (PredictRequest req)
Definition at line 74 of file predict_outcome.py.
References src.predict_outcome._build_base_feature_row(), src.predict_outcome._load_matches_for_prediction(), src.predict_outcome._resolve_best_of(), src.predict_outcome._resolve_player(), and src.predict_outcome._resolve_target_date().
Variable Documentation
RECENT_FEATURE_MAP
dict src.predict_outcome.RECENT_FEATURE_MAP = {}
Definition at line 42 of file predict_outcome.py.