TieBreaker AI: src.features_recent Namespace Reference
src.features_recent Namespace Reference
Classes
class RecentConfig
Functions
pd.DataFrame add_recent_form_features (pd.DataFrame matches, pd.DataFrame dataset, int lookback_matches=20, int min_matches=5)
pd.DataFrame _build_player_history (pd.DataFrame matches)
Dict[str, Any]|None _build_player_record (Dict[str, Any] record, str role, pd.Timestamp date, str|None surface)
float|None _second_serve_attempts (Dict[str, Any] record, str prefix)
int|None _safe_player_id (Any value)
Dict[int, pd.DataFrame] _group_history_by_player (pd.DataFrame history)
Dict[str, Any] _compute_recent_stats (pd.DataFrame|None history, pd.Timestamp|None target_date, str|None surface, RecentConfig cfg)
float _safe_ratio (Any num, Any denom)
float _diff_or_nan (Any val_a, Any val_b)
Variables
dict RECENT_FEATURE_MAP
Detailed Description
Recent form feature utilities for TieBreaker.
Function Documentation
_build_player_history()
pd.DataFrame src.features_recent._build_player_history (pd.DataFrame matches) protected
Definition at line 68 of file features_recent.py.
References src.features_recent._build_player_record().
Referenced by src.features_recent.add_recent_form_features().
_build_player_record()
Dict[str, Any] | None src.features_recent._build_player_record (Dict[str, Any] record, str role, pd.Timestamp date, str | None surface) protected
Definition at line 96 of file features_recent.py.
References src.features_recent._safe_player_id(), src.features_recent._safe_ratio(), and src.features_recent._second_serve_attempts().
Referenced by src.features_recent._build_player_history().
_compute_recent_stats()
Dict[str, Any] src.features_recent._compute_recent_stats (pd.DataFrame | None history, pd.Timestamp | None target_date, str | None surface, RecentConfig cfg) protected
Definition at line 153 of file features_recent.py.
Referenced by src.features_recent.add_recent_form_features().
_diff_or_nan()
float src.features_recent._diff_or_nan (Any val_a, Any val_b) protected
Definition at line 191 of file features_recent.py.
Referenced by src.features_recent.add_recent_form_features().
_group_history_by_player()
Dict[int, pd.DataFrame] src.features_recent._group_history_by_player (pd.DataFrame history) protected
Definition at line 144 of file features_recent.py.
Referenced by src.features_recent.add_recent_form_features().
_safe_player_id()
int | None src.features_recent._safe_player_id (Any value) protected
Definition at line 130 of file features_recent.py.
Referenced by src.features_recent._build_player_record().
_safe_ratio()
float src.features_recent._safe_ratio (Any num, Any denom) protected
Definition at line 180 of file features_recent.py.
Referenced by src.features_recent._build_player_record().
_second_serve_attempts()
float | None src.features_recent._second_serve_attempts (Dict[str, Any] record, str prefix) protected
Definition at line 118 of file features_recent.py.
Referenced by src.features_recent._build_player_record().
add_recent_form_features()
pd.DataFrame src.features_recent.add_recent_form_features (pd.DataFrame matches, pd.DataFrame dataset, int lookback_matches = 20, int min_matches = 5)
Augment dataset with rolling recent-form differentials.
Definition at line 28 of file features_recent.py.
References src.features_recent._build_player_history(), src.features_recent._compute_recent_stats(), src.features_recent._diff_or_nan(), and src.features_recent._group_history_by_player().
Variable Documentation
RECENT_FEATURE_MAP
dict src.features_recent.RECENT_FEATURE_MAP
Initial value:
=  {
    "win_rate": "win_rate_20_diff",
    "win_rate_surface": "win_rate_surface_20_diff",
    "first_in_pct": "first_in_pct_20_diff",
    "first_won_pct": "first_won_pct_20_diff",
    "second_won_pct": "second_won_pct_20_diff",
    "aces_per_SvGm": "aces_per_SvGm_20_diff",
    "df_per_SvGm": "df_per_SvGm_20_diff",
}
Definition at line 11 of file features_recent.py.