TieBreaker AI: src.build_dataset Namespace Reference
src.build_dataset Namespace Reference
Classes
class PlayerLookup
Functions
str normalize_name (str|None value)
pd.Timestamp parse_date_like (Any value)
pd.Timestamp parse_dob_value (Any value)
pd.DataFrame prepare_rankings (pd.DataFrame rankings)
dict[str, Any] _build_ranking_cache (pd.DataFrame df)
dict[str, Any] _get_ranking_cache (pd.DataFrame df)
pd.Series|None _select_latest_before (pd.DataFrame group, pd.Timestamp target, int|None window_days=None)
list[str] _name_variants (str player_name)
dict[str, Any] get_rank_on_or_before (pd.DataFrame rankings, int|None player_id, str player_name, date|datetime|pd.Timestamp|None match_date)
tuple[pd.DataFrame, PlayerLookup] prepare_players (pd.DataFrame players)
str _resolve_player_name (str player_name, int|None player_id, PlayerLookup lookup)
pd.Timestamp|None _resolve_player_dob (str player_name, int|None player_id, PlayerLookup lookup)
float compute_age (pd.Timestamp|None dob, pd.Timestamp|None match_date)
int|None _safe_int (Any value)
dict[str, Any] canonicalize_ab (Mapping[str, Any] row, pd.DataFrame rankings, PlayerLookup players_lookup)
pd.DataFrame build_dataset (pd.DataFrame matches, pd.DataFrame rankings, PlayerLookup players_lookup, int|None limit=None)
pd.DataFrame add_one_hot_features (pd.DataFrame df)
pd.DataFrame add_derived_features (pd.DataFrame df)
str describe_dataframe (pd.DataFrame df)
None save_dataset (pd.DataFrame df, Path out_path)
pd.DataFrame run (Path data_root, list[int]|None years, bool include_all_years, int|None limit, Path out_path, int|None min_year=None, int|None max_year=None)
argparse.ArgumentParser build_parser ()
int main (list[str]|None argv=None)
Detailed Description
TieBreaker dataset builder — constructs an A vs B modelling table from ATP matches.
Function Documentation
_build_ranking_cache()
dict[str, Any] src.build_dataset._build_ranking_cache (pd.DataFrame df) protected
Definition at line 93 of file build_dataset.py.
Referenced by src.build_dataset._get_ranking_cache().
_get_ranking_cache()
dict[str, Any] src.build_dataset._get_ranking_cache (pd.DataFrame df) protected
Definition at line 111 of file build_dataset.py.
References src.build_dataset._build_ranking_cache().
Referenced by src.build_dataset.get_rank_on_or_before().
_name_variants()
list[str] src.build_dataset._name_variants (str player_name) protected
Definition at line 137 of file build_dataset.py.
Referenced by src.build_dataset.get_rank_on_or_before().
_resolve_player_dob()
pd.Timestamp | None src.build_dataset._resolve_player_dob (str player_name, int | None player_id, PlayerLookup lookup) protected
Definition at line 236 of file build_dataset.py.
Referenced by src.build_dataset.canonicalize_ab().
_resolve_player_name()
str src.build_dataset._resolve_player_name (str player_name, int | None player_id, PlayerLookup lookup) protected
Definition at line 229 of file build_dataset.py.
Referenced by src.build_dataset.canonicalize_ab().
_safe_int()
int | None src.build_dataset._safe_int (Any value) protected
Definition at line 252 of file build_dataset.py.
Referenced by src.build_dataset.canonicalize_ab().
_select_latest_before()
pd.Series | None src.build_dataset._select_latest_before (pd.DataFrame group, pd.Timestamp target, int | None window_days = None) protected
Definition at line 119 of file build_dataset.py.
Referenced by src.build_dataset.get_rank_on_or_before().
add_derived_features()
pd.DataFrame src.build_dataset.add_derived_features (pd.DataFrame df)
Add lightweight numeric interactions to boost model signal.
Definition at line 411 of file build_dataset.py.
add_one_hot_features()
pd.DataFrame src.build_dataset.add_one_hot_features (pd.DataFrame df)
Definition at line 397 of file build_dataset.py.
build_dataset()
pd.DataFrame src.build_dataset.build_dataset (pd.DataFrame matches, pd.DataFrame rankings, PlayerLookup players_lookup, int | None limit = None)
Definition at line 384 of file build_dataset.py.
build_parser()
argparse.ArgumentParser src.build_dataset.build_parser ()
Definition at line 522 of file build_dataset.py.
Referenced by src.build_dataset.main().
canonicalize_ab()
dict[str, Any] src.build_dataset.canonicalize_ab (Mapping[str, Any] row, pd.DataFrame rankings, PlayerLookup players_lookup)
Definition at line 264 of file build_dataset.py.
References src.build_dataset._resolve_player_dob(), src.build_dataset._resolve_player_name(), src.build_dataset._safe_int(), src.build_dataset.compute_age(), src.build_dataset.get_rank_on_or_before(), and src.build_dataset.parse_date_like().
compute_age()
float src.build_dataset.compute_age (pd.Timestamp | None dob, pd.Timestamp | None match_date)
Definition at line 243 of file build_dataset.py.
Referenced by src.build_dataset.canonicalize_ab().
describe_dataframe()
str src.build_dataset.describe_dataframe (pd.DataFrame df)
Definition at line 455 of file build_dataset.py.
Referenced by src.build_dataset.run().
get_rank_on_or_before()
dict[str, Any] src.build_dataset.get_rank_on_or_before (pd.DataFrame rankings, int | None player_id, str player_name, date | datetime | pd.Timestamp | None match_date)
Retourne {'rank': int|NaN, 'points': int|NaN, 'ranking_date': date|NaT}
Definition at line 151 of file build_dataset.py.
References src.build_dataset._get_ranking_cache(), src.build_dataset._name_variants(), src.build_dataset._select_latest_before(), and src.build_dataset.parse_date_like().
Referenced by src.build_dataset.canonicalize_ab().
main()
int src.build_dataset.main (list[str] | None argv = None)
Definition at line 534 of file build_dataset.py.
References src.build_dataset.build_parser(), and src.build_dataset.run().
normalize_name()
str src.build_dataset.normalize_name (str | None value)
Definition at line 34 of file build_dataset.py.
parse_date_like()
pd.Timestamp src.build_dataset.parse_date_like (Any value)
Definition at line 40 of file build_dataset.py.
Referenced by src.build_dataset.canonicalize_ab(), and src.build_dataset.get_rank_on_or_before().
parse_dob_value()
pd.Timestamp src.build_dataset.parse_dob_value (Any value)
Definition at line 52 of file build_dataset.py.
prepare_players()
tuple[pd.DataFrame, PlayerLookup] src.build_dataset.prepare_players (pd.DataFrame players)
Definition at line 200 of file build_dataset.py.
prepare_rankings()
pd.DataFrame src.build_dataset.prepare_rankings (pd.DataFrame rankings)
Definition at line 77 of file build_dataset.py.
run()
pd.DataFrame src.build_dataset.run (Path data_root, list[int] | None years, bool include_all_years, int | None limit, Path out_path, int | None min_year = None, int | None max_year = None)
Definition at line 489 of file build_dataset.py.
References src.build_dataset.describe_dataframe(), and src.build_dataset.save_dataset().
Referenced by src.build_dataset.main().
save_dataset()
None src.build_dataset.save_dataset (pd.DataFrame df, Path out_path)
Definition at line 484 of file build_dataset.py.
Referenced by src.build_dataset.run().