TieBreaker AI: src.tiebreaker_cli Namespace Reference
src.tiebreaker_cli Namespace Reference
Functions
str norm (str s)
str|None best_name_match (str query, list[str] candidates)
date_parse_or_none (str|None s)
resolve_player_id (DataHub hub, str name_query)
cmd_rank (args, DataHub hub)
cmd_match (args, DataHub hub)
_load_model_bundle_or_exit (str|Path path_value)
_predict_proba_from_joblib_model (model_obj, X)
_build_eval_xy (Path|None data_root=None, int|None years=6)
str _format_model_load_error (str|Path model_path, Exception exc)
cmd_comparison_models (args, DataHub hub)
cmd_predict (args, DataHub hub)
build_parser ()
main (argv=None)
Variables
evaluate_binary_prob_model = None
bootstrap_ci_diff = None
Function Documentation
_build_eval_xy()
src.tiebreaker_cli._build_eval_xy (Path | None data_root = None, int | None years = 6) protected
Build an evaluation dataset compatible with testLib's DecisionTree.
We reuse testLib's training sample generation so the feature set is numeric and stable.
Definition at line 172 of file tiebreaker_cli.py.
Referenced by src.tiebreaker_cli.cmd_comparison_models().
_format_model_load_error()
str src.tiebreaker_cli._format_model_load_error (str | Path model_path, Exception exc) protected
Return a user-friendly message for common pickle/joblib incompatibilities.
Definition at line 193 of file tiebreaker_cli.py.
Referenced by src.tiebreaker_cli.cmd_comparison_models().
_load_model_bundle_or_exit()
src.tiebreaker_cli._load_model_bundle_or_exit (str | Path path_value) protected
Definition at line 148 of file tiebreaker_cli.py.
Referenced by src.tiebreaker_cli.cmd_comparison_models().
_predict_proba_from_joblib_model()
src.tiebreaker_cli._predict_proba_from_joblib_model (model_obj, X) protected
Return P(class=1) for a variety of sklearn-like estimators.
Definition at line 159 of file tiebreaker_cli.py.
Referenced by src.tiebreaker_cli.cmd_comparison_models().
best_name_match()
str | None src.tiebreaker_cli.best_name_match (str query, list[str] candidates)
Definition at line 41 of file tiebreaker_cli.py.
References src.tiebreaker_cli.norm().
Referenced by src.tiebreaker_cli.resolve_player_id().
build_parser()
src.tiebreaker_cli.build_parser ()
Definition at line 408 of file tiebreaker_cli.py.
Referenced by src.tiebreaker_cli.main().
cmd_comparison_models()
src.tiebreaker_cli.cmd_comparison_models (args, DataHub hub)
Definition at line 211 of file tiebreaker_cli.py.
References src.tiebreaker_cli._build_eval_xy(), src.tiebreaker_cli._format_model_load_error(), src.tiebreaker_cli._load_model_bundle_or_exit(), and src.tiebreaker_cli._predict_proba_from_joblib_model().
cmd_match()
src.tiebreaker_cli.cmd_match (args, DataHub hub)
Definition at line 113 of file tiebreaker_cli.py.
References src.tiebreaker_cli.resolve_player_id().
cmd_predict()
src.tiebreaker_cli.cmd_predict (args, DataHub hub)
Definition at line 353 of file tiebreaker_cli.py.
cmd_rank()
src.tiebreaker_cli.cmd_rank (args, DataHub hub)
Definition at line 66 of file tiebreaker_cli.py.
References src.tiebreaker_cli.date_parse_or_none(), and src.tiebreaker_cli.resolve_player_id().
date_parse_or_none()
src.tiebreaker_cli.date_parse_or_none (str | None s)
Definition at line 49 of file tiebreaker_cli.py.
Referenced by src.tiebreaker_cli.cmd_rank().
main()
src.tiebreaker_cli.main (argv = None)
Definition at line 450 of file tiebreaker_cli.py.
References src.tiebreaker_cli.build_parser().
norm()
str src.tiebreaker_cli.norm (str s)
Definition at line 38 of file tiebreaker_cli.py.
Referenced by src.tiebreaker_cli.best_name_match().
resolve_player_id()
src.tiebreaker_cli.resolve_player_id (DataHub hub, str name_query)
Definition at line 57 of file tiebreaker_cli.py.
References src.tiebreaker_cli.best_name_match().
Referenced by src.tiebreaker_cli.cmd_match(), and src.tiebreaker_cli.cmd_rank().
Variable Documentation
bootstrap_ci_diff
src.tiebreaker_cli.bootstrap_ci_diff = None
Definition at line 36 of file tiebreaker_cli.py.
evaluate_binary_prob_model
src.tiebreaker_cli.evaluate_binary_prob_model = None
Definition at line 35 of file tiebreaker_cli.py.